"""book table added

Revision ID: 95cb058a8173
Revises: 1a31ce608336
Create Date: 2025-09-16 04:14:30.274676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95cb058a8173'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=True),
                    sa.Column('published_year', sa.Integer(), nullable=False),
                    sa.Column('book_id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('book_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
